### ISSUE TITLE
Abnormal amount of KCM real-time data missing

### ISSUE THREAD

**Issue by bbodenmiller** [SoundTransit/soundtransit-rds#14]
I've noticed an abnormal amount of real-time data missing the last week. I haven't seen data for the 124 for at least a week but I've also noticed more other routes missing data than usual. Has there been some sort of data import error?

**Comment by petedussin** [comment]
Real time should be improved today. A bundle was released that addressed some problems between the way the bundle had previously been built and the requirements of the new, detailed holiday scheduling.

**Comment by bbodenmiller** [comment]
Any chance pieces of the bundle build process might be open sourced?

**Comment by sheldonabrown** [comment]
It is:

https://github.com/camsys/onebusaway-nyc/tree/master/onebusaway-nyc-admin-webapp
