### ISSUE TITLE
Include WSDOT ferry realtime data

### ISSUE THREAD

**Issue by bbodenmiller** [SoundTransit/soundtransit-rds#22]
Would be great to include realtime ferry data. WSDOT provides some data already via [VesselWatch](http://www.wsdot.com/ferries/vesselwatch/Default.aspx) so it is likely just a matter of working with them to provide the data in the appropriate format.

**Comment by michaelberman** [comment]
Ben, this is in our current backlog. We hope to have it within the next 6 months.

Thanks,
Michael

On Mar 23, 2015 11:31 PM, Ben Bodenmiller <notifications@github.com> wrote:

Would be great to include realtime ferry data. WSDOT provides some data already via VesselWatch<http://www.wsdot.com/ferries/vesselwatch/Default.aspx> so it is likely just a matter of working with them to provide the data in the appropriate format.

-

**Comment by bbodenmiller** [comment]
:+1: 

Would it be possible for Sound Transit to start publishing backlogs/roadmaps? It'd be much easier than me guessing what is in the pipeline.

/cc @aaronbrethorst

**Comment by aaronbrethorst** [comment]
I'd love to see that too, especially given my desire to incorporate OTP-based functionality into OneBusAway. Congrats on the launch of your trip planner app, btw.

**Comment by bbodenmiller** [comment]
FYI per https://github.com/WSDOT/wsdot-website/issues/42 [WSDOT Traveler Information API](http://www.wsdot.wa.gov/traffic/api/) is the best way to get the ferry.

**Comment by bbodenmiller** [comment]
I emailed WSDOT & they mentioned the GTFS feed Google uses for schedule data is at https://business.wsdot.wa.gov/Transit/csv_files/WSF/google_transit.zip. OBA can import GTFS schedule data relatively easily, correct?

**Comment by JulietChase** [comment]
Hi Ben,

The ferry data is in the works and should be released shortly. There are both short and long term projects in the works to improve communication of status and planning in this area.  Thanks for your patience :-)

Regards,
Juliet

From: Ben Bodenmiller
Reply-To: SoundTransit/soundtransit-rds
Date: Thursday, April 23, 2015 at 10:04 AM
To: SoundTransit/soundtransit-rds
Subject: Re: [soundtransit-rds] Include WSDOT ferry realtime data (#22)


I emailed WSDOT & they mentioned the GTFS feed Google uses for schedule data is at https://business.wsdot.wa.gov/Transit/csv_files/WSF/google_transit.zip. OBA can import GTFS schedule data relatively easily, correct?

**Comment by JulietChase** [comment]
closing this as we now have WA State Ferries in real-time in OBA ....

**Comment by bbodenmiller** [comment]
@JulietChase this would be a cool thing to make sure Seattle Transit Blog is aware of so they could make users aware of the new feature.
