### ISSUE TITLE
GTFS-rt doesn't contain data for "on time" trips

### ISSUE THREAD

**Issue by gcamp** [SoundTransit/soundtransit-rds#24]
Hey guys, @bbodenmiller pointed me here to submit issues on the data. 

One problem we are seeing is that the GTFS-rt is not containing data for trips that are considered "on time". Even if it would not change the ETA displayed in an app, there's a big difference for the user to know if that ETA is based on real time information or only schedule information.

**Comment by sheldonabrown** [comment]
Do you happen to have an example handy?

**Comment by gcamp** [comment]
Double checked and I'm not seeing the problem anymore. Either I last checked last time or it was fixed since then.
