### ISSUE TITLE
Community Transit stop names with trailing & character

### ISSUE THREAD

**Issue by bdferris** [SoundTransit/soundtransit-rds#27]
There are a number of stops in the CT GTFS feed with trailing & characters:

1748,Boeing Gate E-67 &,47.914313,-122.276825
2035,Lynnwood Transit Center &,47.815955,-122.296434
2038,Mariner P&R &,47.879858,-122.238806
2039,McCollum Park P&R &,47.879289,-122.220698
2058,Smokey Point Transit Ctr &,48.154639,-122.184036
2327,Boeing Gate E-72 &,47.925797,-122.280678
2328,Boeing Gate E-84 &,47.932338,-122.278613
2330,Boeing Gate E-88 &,47.931631,-122.265929
...

I'm not sure if this is an issue with the converter or the underlying data.  I'm not sure if the CT GIS + Schedule files are publicly available, but if I can get a recent version, I can try to help debug / submit patches to fix this as needed.

**Comment by JulietChase** [comment]
Thanks for identifying these - they've been added to the queue and should be addressed shortly.

**Comment by sheldonabrown** [comment]
I've updated HastusGtfsFactory to fix this.  The next bundle will fix this, I'll keep the issue open until then.

**Comment by sheldonabrown** [comment]
Actually, using the post-processed version of this GTFS fixes the issue as well.  The public version is now correct.
