### ISSUE TITLE
Everett Transit GTFS data expired

### ISSUE THREAD

**Issue by bbodenmiller** [SoundTransit/soundtransit-rds#28]
The Everett Transit data at http://www.soundtransit.org/Developer-resources/Data-downloads is expired and has other errors per the [Google FeedValidator](https://github.com/google/transitfeed/wiki/FeedValidator). This is preventing many apps that would hopefully add Everett Transit data from doing so. /cc @gcamp

Google FeedValidator results:

GTFS validation results for feed:<br>
<code><span class="path">C:\Users\Ben\Downloads\97_gtfs.zip</code><br>
FeedValidator extension used: None
<br><br>
<table>
<tr><th class="header">Agencies:</th><td class="header"><a href="http://www.everetttransit.org">Everett Transit</a></td></tr>
<tr><th class="header">Routes:</th><td class="header">13</td></tr>
<tr><th class="header">Stops:</th><td class="header">615</td></tr>
<tr><th class="header">Trips:</th><td class="header">695</td></tr>
<tr><th class="header">Shapes:</th><td class="header">40</td></tr>
<tr><th class="header">Effective:</th><td class="header">August 24, 2014 to February 21, 2015</td></tr>
</table>

<br>
<span class="fail">Found these problems:</span>
<table class="count_outside">
<tr><td><span class="fail">121 errors</span></td><td><span class="fail">1490 warnings</span></td></tr>
<tr><td>
<table><tr><td>121</td><td><a href="#ErrorInvalidValue">Invalid Values</a></td></tr>
</table>
</td>
<td>
<table><tr><td>1</td><td><a href="#WarningExpirationDate">Expiration Date</a></td></tr>
<tr><td>131</td><td><a href="#WarningInvalidValue">Invalid Values</a></td></tr>
<tr><td>9</td><td><a href="#WarningOtherProblem">Other Problems</a></td></tr>
<tr><td>1321</td><td><a href="#WarningStopTooFarFromShapeWithDistTraveled">Stop Too Far From Shape With Dist Traveleds</a></td></tr>
<tr><td>21</td><td><a href="#WarningTooFastTravel">Too Fast Travels</a></td></tr>
<tr><td>7</td><td><a href="#WarningUnusedStop">Unused Stops</a></td></tr>
</table>
</td>
</table>
<br><br>
<h3 class="issueHeader">Errors:</h3><h4 class="issueHeader"><a name="ErrorInvalidValue">Invalid Value</a></h4><ul>
<li><div class="problem">Invalid value 0.0 in field <code>stoptimes.shape_dist_traveled</code><br>For the trip RT3WDSB02_68VR_T01 the stop 1510 has shape_dist_traveled=0.0, which should be larger than the previous ones. In this case, the previous distance was 21.273.</div><br></li>
<li><div class="problem">Invalid value 0.999 in field <code>stoptimes.shape_dist_traveled</code><br>For the trip RT3WDSB02_68VR_T01 the stop 1530 has shape_dist_traveled=0.999, which should be larger than the previous ones. In this case, the previous distance was 21.273.</div><br></li>
<li><div class="problem">Invalid value 1.404 in field <code>stoptimes.shape_dist_traveled</code><br>For the trip RT3WDSB02_68VR_T01 the stop 1540 has shape_dist_traveled=1.404, which should be larger than the previous ones. In this case, the previous distance was 21.273.</div><br></li>
<li><div class="problem">Invalid value 1.79 in field <code>stoptimes.shape_dist_traveled</code><br>For the trip RT3WDSB02_68VR_T01 the stop 1545 has shape_dist_traveled=1.79, which should be larger than the previous ones. In this case, the previous distance was 21.273.</div><br></li>
<li><div class="problem">Invalid value 2.031 in field <code>stoptimes.shape_dist_traveled</code><br>For the trip RT3WDSB02_68VR_T01 the stop 3030 has shape_dist_traveled=2.031, which should be larger than the previous ones. In this case, the previous distance was 21.273.</div><br></li>
<li>and 116 more of this type.</ul>
<h3 class="issueHeader">Warnings:</h3><h4 class="issueHeader"><a name="WarningExpirationDate">Expiration Date</a></h4><ul>
<li><div class="problem">This feed expired on February 21, 2015 (last service date in calendar.txt)</div><br></li>
</ul>
<h4 class="issueHeader"><a name="WarningInvalidValue">Invalid Value</a></h4><ul>
<li><div class="problem">Invalid value 6.734 in field <code>stoptimes.shape_dist_traveled</code><br>For the trip RT3WDSB02_68_T03 the stop 3567 has shape_dist_traveled=6.734, which should be larger than the previous ones. In this case, the previous distance was 6.734.</div><br></li>
<li><div class="problem">Invalid value 6.734 in field <code>stoptimes.shape_dist_traveled</code><br>For the trip RT3WDSB02_68_T03 the stop 3580 has shape_dist_traveled=6.734, which should be larger than the previous ones. In this case, the previous distance was 6.734.</div><br></li>
<li><div class="problem">Invalid value 18.179 in field <code>stoptimes.shape_dist_traveled</code><br>For the trip RT3WDSB02_68_T02 the stop 3006 has shape_dist_traveled=18.179, which should be larger than the previous ones. In this case, the previous distance was 18.179.</div><br></li>
<li><div class="problem">Invalid value 18.179 in field <code>stoptimes.shape_dist_traveled</code><br>For the trip RT3WDSB02_68_T02 the stop 2275 has shape_dist_traveled=18.179, which should be larger than the previous ones. In this case, the previous distance was 18.179.</div><br></li>
<li><div class="problem">Invalid value 18.358 in field <code>stoptimes.shape_dist_traveled</code><br>For the trip RT3WDSB02_68_T02 the stop 1290 has shape_dist_traveled=18.358, which should be larger than the previous ones. In this case, the previous distance was 18.358.</div><br></li>
<li>and 126 more of this type.</ul>
<h4 class="issueHeader"><a name="WarningOtherProblem">Other Problem</a></h4><ul>
<li><div class="problem">In stop_times.txt, the stop with trip_id=RT18WDWB01_T07 and stop_sequence=33 has shape_dist_traveled=12.267000, which is larger than the max shape_dist_traveled=11.016000 of the corresponding shape (shape_id=RT18WB01)</div><br></li>
<li><div class="problem">In stop_times.txt, the stop with trip_id=RT8SUSB02_T01 and stop_sequence=50 has shape_dist_traveled=17.920000, which is larger than the max shape_dist_traveled=16.617000 of the corresponding shape (shape_id=RT8SB02)</div><br></li>
<li><div class="problem">In stop_times.txt, the stop with trip_id=RT17WDNB01_T07 and stop_sequence=38 has shape_dist_traveled=11.558000, which is larger than the max shape_dist_traveled=11.084000 of the corresponding shape (shape_id=RT17NB01)</div><br></li>
<li><div class="problem">In stop_times.txt, the stop with trip_id=RT2WDCC01_T01 and stop_sequence=34 has shape_dist_traveled=14.898000, which is larger than the max shape_dist_traveled=13.125000 of the corresponding shape (shape_id=RT2CC01)</div><br></li>
<li><div class="problem">In stop_times.txt, the stop with trip_id=RT12SACW01_T10 and stop_sequence=41 has shape_dist_traveled=13.960000, which is larger than the max shape_dist_traveled=11.972000 of the corresponding shape (shape_id=RT12CW01)</div><br></li>
<li>and 4 more of this type.</ul>
<h4 class="issueHeader"><a name="WarningStopTooFarFromShapeWithDistTraveled">Stop Too Far From Shape With Dist Traveled</a></h4><ul>
<li><div class="problem">For trip RT29WDNB02_T01 the stop "111th ST SE and 9TH AVE SE" (ID 6330) is 12261 meters away from the corresponding point (shape_dist_traveled: 18.641000) on shape RT29NB02. It should be closer than 1000 meters.</div><br></li>
<li><div class="problem">For trip RT29WDSB01_ALL_T03 the stop "6th AVE SE and 112TH ST SE" (ID 6170) is 12208 meters away from the corresponding point (shape_dist_traveled: 0.000000) on shape RT29SB01_ALL. It should be closer than 1000 meters.</div><br></li>
<li><div class="problem">For trip RT29WDNB02_T01 the stop "111th ST SE and SILVER LAKE ROAD" (ID 6335) is 12188 meters away from the corresponding point (shape_dist_traveled: 18.641000) on shape RT29NB02. It should be closer than 1000 meters.</div><br></li>
<li><div class="problem">For trip RT29WDNB02_T01 the stop "111th ST SE and 16TH AVE SE" (ID 6337) is 12143 meters away from the corresponding point (shape_dist_traveled: 18.641000) on shape RT29NB02. It should be closer than 1000 meters.</div><br></li>
<li><div class="problem">For trip RT29WDNB02_T01 the stop "6th AVE SE and 110TH ST SE" (ID 6325) is 12103 meters away from the corresponding point (shape_dist_traveled: 18.641000) on shape RT29NB02. It should be closer than 1000 meters.</div><br></li>
<li>and 1316 more of this type.</ul>
<h4 class="issueHeader"><a name="WarningTooFastTravel">Too Fast Travel</a></h4><ul>
<li><div class="problem">High speed travel detected in trip RT8WDSB01_T06: E CASINO RD and EVERGREEN WAY to AIRPORT RD and EVERGREEN WAY. 4106 meters in 60 seconds. (246 km/h).</div><br></li>
<li><div class="problem">High speed travel detected in trip RT8WDSB01_T05: E CASINO RD and EVERGREEN WAY to AIRPORT RD and EVERGREEN WAY. 4106 meters in 60 seconds. (246 km/h).</div><br></li>
<li><div class="problem">High speed travel detected in trip RT8WDSB01_T04: E CASINO RD and EVERGREEN WAY to AIRPORT RD and EVERGREEN WAY. 4106 meters in 60 seconds. (246 km/h).</div><br></li>
<li><div class="problem">High speed travel detected in trip RT8WDSB01_T07: E CASINO RD and EVERGREEN WAY to AIRPORT RD and EVERGREEN WAY. 4106 meters in 60 seconds. (246 km/h).</div><br></li>
<li><div class="problem">High speed travel detected in trip RT8WDSB01_T09: E CASINO RD and EVERGREEN WAY to AIRPORT RD and EVERGREEN WAY. 4106 meters in 60 seconds. (246 km/h).</div><br></li>
<li>and 16 more of this type.</ul>
<h4 class="issueHeader"><a name="WarningUnusedStop">Unused Stop</a></h4><ul>
<li><div class="problem">COLLEGE STATION - BAY A (ID 1051) isn't used in any trips</div><br></li>
<li><div class="problem">COLLEGE STATION - BAY D (ID 1054) isn't used in any trips</div><br></li>
<li><div class="problem">COLLEGE STATION - BAY E (ID 1055) isn't used in any trips</div><br></li>
<li><div class="problem">BROADWAY and TOWER ST (ID 1057) isn't used in any trips</div><br></li>
<li><div class="problem">BROADWAY and TOWER (ID 1058) isn't used in any trips</div><br></li>
<li>and 2 more of this type.</ul>

<div class="footer">
Generated by <a href="https://github.com/google/transitfeed/wiki/FeedValidator">
FeedValidator</a> version 1.2.15 on April 27, 2015 at 12:26 AM Pacific Daylight Time.
</div>

**Comment by sheldonabrown** [comment]
The GTFS files have been updated.  The hosting location of these GTFS files
is temporary while we work on a permanent arrangement, so I apologize for
them falling out of date.

As for the warnings mentioned above -- you'll need to contact Evertt
Transit directly.  Do note that these are not critical errors with respect
to OneBusAway.

Sheldon

**Comment by bbodenmiller** [comment]
Thanks for getting this updated. FYI Transit App added Everett Transit today.

**Comment by sheldonabrown** [comment]
As an FYI, I've scripted the update of this GTFS so it will stay in sync with what OBA is serving.
