### ISSUE TITLE
Missing "transfers" column in "fare_attributes.txt" file of modified ST GTFS feed

### ISSUE THREAD

**Issue by bdferris** [SoundTransit/soundtransit-rds#29]
In the latest ST GTFS feed downloaded from:

http://developer.onebusaway.org/tmp/sound/gtfs/modified/40_gtfs.zip

The `fare_attributes.txt` file is missing the `transfers` column.  As noted in the [GTFS spec](https://developers.google.com/transit/gtfs/reference#fare_attributes_fields), this column is required and the feed will fail to validate without it.

**Comment by sheldonabrown** [comment]
In the GTFS feed provided by ST, the column is present but empty.  When running it through the GTFS modifier for cleanup the column is then dropped, perhaps due to it being empty.

I'll see if ST can add values here.

**Comment by sheldonabrown** [comment]
Reading the spec present-but-empty implies unlimited transfers, so this appears to be a bug in the GTFS modified.

**Comment by bdferris** [comment]
This might also be a bug in the GTFS transformer.  If the field is present but empty in the source GTFS, it should be kept around in the transformer.  I can take a look into fixing that since I'm messing with the transformer this week.

**Comment by sheldonabrown** [comment]
That would be greatly appreciated!

**Comment by bdferris** [comment]
Ok, fix on the transformer side is in.  I'm going to cut a new release of OBA GTFS modules since it includes a couple new things.

**Comment by bdferris** [comment]
New onebusaway-gtfs-transformer-cli-1.3.4 release containing the transfer column fix is.  Any chance you can update the modified ST GTFS feed?

**Comment by sheldonabrown** [comment]
Absolutely.  It wont be right away however.  The public GTFS is now tied to
the currently deployed bundle, so I'll need to push a new bundle first.  I
plan to do that Thursday as it is -- it that soon enough?

**Comment by bdferris** [comment]
Yeah, that's should be fine.  Thanks!

**Comment by sheldonabrown** [comment]
@brianferris GTFS went out this morning.  Let me know if you have any
problems.

Sheldon

**Comment by bdferris** [comment]
Can confirm that the new feed is working.  Thanks!
