### ISSUE TITLE
King County Metro route 916 not included

### ISSUE THREAD

**Issue by JulietChase** [SoundTransit/soundtransit-rds#31]
Received via email to Sound Transit: route 916 is missing

***
route 916 is KCM serving the local Kent area

**Comment by bbodenmiller** [comment]
I'm seeing 916 in the Transit App & OBA. I just don't see realtime for them.

![image](https://cloud.githubusercontent.com/assets/1192780/7503788/13620010-f3fa-11e4-9e3d-b4b2dcdfce82.jpg)
![image](https://cloud.githubusercontent.com/assets/1192780/7503789/1362766c-f3fa-11e4-8bc9-7c36daf79cbf.jpg)

**Comment by JulietChase** [comment]
closing - 916 is present and accounted for - KCM confirms that real-time is not available for DART/900 series routes
