### ISSUE TITLE
User reported list of real-time accuracy issues & ghost buses

### ISSUE THREAD

**Issue by JulietChase** [SoundTransit/soundtransit-rds#32]
Received via email to Sound Transit - as these are relatively generic reports this is a compiled list for reference:

Route 12 - not showing real-time arrivals
Route 14 - inaccurate
Route 71 - only shows real-time after it has left, prior to that it's schedule time only
Route 75 - inaccurate (specifically reported from stop 9800 on Sand Point Way & NE 103rd St.
Route 99 - inaccurate / ghost buses
Route 540 - inaccurate/ ghost buses

**Comment by bbodenmiller** [comment]
There must be thousands of reports like these. I know I've given up on reporting problems I see as it doesn't seem to make a difference.

In particular there is always accuracy issues when a bus is on a reroute or stuck in traffic (arrival prediction does not seem to take in to account current speed). Additionally I either don't see realtime data while a bus is on a layover or if I do it shows as being late but sometimes leaves layover ontime.

**Comment by bbodenmiller** [comment]
Related to layover issues: https://github.com/SoundTransit/soundtransit-rds/issues/3, https://github.com/OneBusAway/onebusaway-application-modules/issues/6

**Comment by JulietChase** [comment]
closing - ghost busses need their own research strategy (unfortunately!)
