### ISSUE TITLE
Add Microsoft Shuttles schedule data

### ISSUE THREAD

**Issue by cookieguru** [SoundTransit/soundtransit-rds#33]
See [cookieguru/microsoft-gtfs](https://github.com/cookieguru/microsoft-gtfs)

There seems to be minor interest [amongst STB readers](http://seattletransitblog.com/2015/05/19/gtfs-for-microsoft-shuttles/).  If this is integrated, I hope `privateService` could be set to `true`.  On that note, a) Why is Children's part of OBA and b) Why isn't it marked private?  It's also worth mentioning that I'm not exactly sure what the `privateService` flag is for since it's not documented anywhere [in](https://github.com/OneBusAway/onebusaway-application-modules/blob/master/src/site/markdown/api/where/methods/agencies-with-coverage.md) [the](https://github.com/OneBusAway/onebusaway-application-modules/blob/master/src/site/markdown/api/where/methods/agency.md) [docs](https://github.com/OneBusAway/onebusaway-application-modules/blob/master/src/site/markdown/api/where/elements/agency.md).

I know @aaronbrethorst is interested in getting this added for integration in to the iOS app.  Perhaps the official apps could add a new tickbox in the settings to "Show private services", and the API docs can be updated so other developers are encouraged to not show private agencies by default?

**Comment by aaronbrethorst** [comment]
Mind pinging me over email? I'd love to chat with you about a couple points of this, and don't want to clutter this Issue up with my questions. thx :)

**Comment by JulietChase** [comment]
Are there still open questions on this? Closing as there hasn't been anything actionable at this point. From a business rules standpoint Children's is free and open to anyone in the public to use; the hospital is also a public agency although not a transit one... If there is a reason to revisit flags please let me know...

**Comment by cookieguru** [comment]
@JulietChase The Children's shuttles are *not* open to the public.  The [Children's Transportation page](http://www.seattlechildrens.org/visitors/transportation/) only makes a brief mention of them as employee shuttles, so they're just as off limits to the general public as the Microsoft shuttles are.

Also, Children's is not a public agency; it is a private non-profit.

**Comment by cookieguru** [comment]
So far as I can tell, these are the only differences:

                           | Microsoft  | Children's
-------------------------- | ---------- | ----------
Ownership                  | Private    | Private
Status                     | For-profit | Non-profit
Operates shuttles          | ✓          | ✓
Shuttles open to employees | ✓          | ✓
Shuttles open to public    | ✗          | ✗
Shuttle data on OBA        | ✓          | ✗
