### ISSUE TITLE
Rename Community Transit Route 701 to Swift

### ISSUE THREAD

**Issue by bdferris** [SoundTransit/soundtransit-rds#34]
Community Transit's Swift BRT route is currently labeled Route 701 on OneBusAway and in the GTFS feed exported by Sound Transit.  See, for example:

http://pugetsound.onebusaway.org/where/standard/#m(route)route(29_701)

It would be cool if ST could fix the route name as part of their regional data services clean-up.

The following transformer rule would do the trick:

    {"op":"update", "match":{"file":"routes.txt", "route_short_name":"701"}, "update":{"route_short_name":"Swift"}}

**Comment by sheldonabrown** [comment]
Thanks Brian,

some beta testing had already pointed this one out, along with some other route name improvements.  They will be corrected the next service change (June 6).

**Comment by bbodenmiller** [comment]
Any chance this will also clear up the light rail station names?

![image](https://cloud.githubusercontent.com/assets/1192780/7963053/a03e9d96-09c5-11e5-90fc-745ddff61050.jpg)

**Comment by sheldonabrown** [comment]
What is the source of that GTFS?  The GTFS that OBA is using does not use those names.  I thought I saw that the feed sent to Google was changing, perhaps that hasn't happened officially yet?

http://pugetsound.onebusaway.org/where/standard/trip.action?id=40_15043837&serviceDate=1433314800000

**Comment by bdferris** [comment]
Moving this discussion back to issue #16.

**Comment by bdferris** [comment]
Marking closed since indeed this was fixed in the June 6 update.
