### ISSUE TITLE
Users reporting strange arrival/departure times

### ISSUE THREAD

**Issue by JulietChase** [SoundTransit/soundtransit-rds#38]
Over the last several weeks we (Sound Transit) have been getting user complaints from within OBA that arrival and departure times are in strange numbers that don't relate to hh:mm time. Some examples are below. There are enough of these and over time, routes, stops to indicate a real problem but we haven't been able to replicate it - at least not with Android or desktop.  Let me know if more examples would be helpful.  
Thanks,
Juliet

id: 29440
                   serviceDate: 1437289200000
          stop_agencyId: 1
                stop_id: 52240
                   time: 1437358362643
          trip_agencyId: 1
                trip_id: 21813567
            userComment: even though I reset the app it still shows all the buses should arrive -8684 minutes ago.

***
id: 749
     stopId_agencyId: 1
           stopId_id: 26210
                time: 1437001844892
         userComment: Bus arrival time isnt being displayed in hours and minutes

***
id: 716
stopId_agencyId: 1
           stopId_id: 22740
                time: 1436792985932
         userComment: It says the bus left 668 minutes ago

**Comment by mukhark** [comment]
Do we know when those problems occurred? It appears as though the dates and times listed are unix epoch times (in milliseconds):

1437289200000 = Sun, 19 Jul 2015
1437358362643 = Mon, 20 Jul 2015 02:12:42 GMT
1437001844892 = Wed, 15 Jul 2015 23:10:44 GMT
1436792985932 = Mon, 13 Jul 2015 13:09:45 GMT

If that is the case, then this may be a s/w issue and not a data issue.

**Comment by JulietChase** [comment]
closing as duplicates other items...
