### ISSUE TITLE
Duplicate Data Sources

### ISSUE THREAD

**Issue by RideSchedules** [SoundTransit/soundtransit-rds#40]
Sound Transit with incomplete routes is in the Pierce Transit GTFS file.  This creates a duplicate data source for Sound Transit.

Any way it can be removed or publish single authoritative sources for both agencies (with OBA compatible identifiers)?

**Comment by JulietChase** [comment]
Sorry for the delay in answering this - Sound Transit is a unique agency in that much of the operational work is done with partner agencies (bus drivers, routes, etc.) consequently the data is contained within those agency files. The ST routes within the Pierce GTFS are those routes run by Pierce Transit on behalf of ST, that is true for Community Transit and King County Metro as well.  There is no real duplication between them as the ST GTFS has only Sounder and T-LINK routes. If you are specifically looking for ST it is necessary to piece together the various agency files to get the whole picture. There is now a combined GTFS available in Beta status that gives a whole world view with a few caveats. If you are looking for just Pierce without the ST 'noise' I don't have much to offer - it would be ideal to have everything better categorized but for now it has to do with how and when the data is generated...

Closing this item now....
