### ISSUE TITLE
Broken shape data in Sound Transit GTFS

### ISSUE THREAD

**Issue by bdferris** [SoundTransit/soundtransit-rds#41]
(Feel free to stop me if you already saw the Google Transit notification about this)

In the latest Sound Transit GTFS feed (http://developer.onebusaway.org/tmp/sound/gtfs/modified/40_gtfs.zip), it appears shape ids for Sounder trains have been mangled/broken.  Specifically, a number of trips in trips.txt are referencing shape_ids like:

SNDR_N_NB_shp
SNDR_N_SB_shp
SNDR_S_NBLW_shp
SNDR_S_NB_shp
SNDR_S_SBLW_shp
SNDR_S_SB_shp

However, in shapes.txt, we shape ids like:

SNDR_EV_NB_shp
SNDR_EV_SB_shp
SNDR_TL_NBLW_shp
SNDR_TL_NB_shp
SNDR_TL_SBLW_shp
SNDR_TL_SB_shp

Note how N/S have been replaced by EV/TL.  Until this is fixed, the SoundTransit feed is invalid.

**Comment by soundtransitdev** [comment]
Brian,

Thanks for the heads up – updated files are now available for download, live OBA should be updated within the hour.

Regards,
Juliet

From: Brian Ferris
Reply-To: SoundTransit/soundtransit-rds
Date: Thursday, July 23, 2015 at 7:16 AM
To: SoundTransit/soundtransit-rds
Subject: [soundtransit-rds] Broken shape data in Sound Transit GTFS (#41)


(Feel free to stop me if you already saw the Google Transit notification about this)

In the latest Sound Transit GTFS feed (http://developer.onebusaway.org/tmp/sound/gtfs/modified/40_gtfs.zip), it appears shape ids for Sounder trains have been mangled/broken. Specifically, a number of trips in trips.txt are referencing shape_ids like:

SNDR_N_NB_shp
SNDR_N_SB_shp
SNDR_S_NBLW_shp
SNDR_S_NB_shp
SNDR_S_SBLW_shp
SNDR_S_SB_shp

However, in shapes.txt, we shape ids like:

SNDR_EV_NB_shp
SNDR_EV_SB_shp
SNDR_TL_NBLW_shp
SNDR_TL_NB_shp
SNDR_TL_SBLW_shp
SNDR_TL_SB_shp

Note how N/S have been replaced by EV/TL. Until this is fixed, the SoundTransit feed is invalid.

**Comment by bdferris** [comment]
I've confirmed that the new feed looks good.
