### ISSUE TITLE
Google Maps timetables out of date

### ISSUE THREAD

**Issue by bbodenmiller** [SoundTransit/soundtransit-rds#42]
Google Maps is reporting "We don't have the most recent timetables for this area."

![image](https://cloud.githubusercontent.com/assets/1192780/10172406/ff9073a2-6693-11e5-9e0f-a308bc9e7921.png)

/cc @bdferris

**Comment by JulietChase** [comment]
We had some technical issues which have now been resolved so the new files were made available to Google yesterday morning (9/28)...

**Comment by bbodenmiller** [comment]
Any chance in the future if the bundle could be merged with the old one before the switch so they have both the old and new schedule data? Since Google allows you to plan trips in the future this would allow validation ahead of time and for people to plan trips in the future.

**Comment by bbodenmiller** [comment]
Looks to be fixed now.
