### ISSUE TITLE
GTFS feed missing F line stop & OBA missing schedule/realtime data for stop

### ISSUE THREAD

**Issue by bbodenmiller** [SoundTransit/soundtransit-rds#46]
OneBusAway is showing an F line stop at Park Ave N & N 6th St however the GTFS feed as of now is not.

GTFS file in [transitfeed schedule viewer](https://github.com/google/transitfeed):
![image](https://cloud.githubusercontent.com/assets/1192780/11019338/2c66e606-85aa-11e5-9e79-127375064bd1.png)
View from Transit App:
![image](https://cloud.githubusercontent.com/assets/1192780/11019368/fa1a51dc-85aa-11e5-9286-9a7470f30a81.png)
View from OneBusAway:
![image](https://cloud.githubusercontent.com/assets/1192780/11019372/10216bb4-85ab-11e5-83e0-42401c7194af.png)

Additionally even though the stop appears in OneBusAway selecting it returns no realtime or scheduled data for F line at that stop.

**Comment by soundtransitdev** [comment]
This one I have an answer for:  There were some limiting service dates in the existing feed which KCM has updated.  We are waiting on a code deployment before updating the data again but this stop should be back in service from a data perspective with trips/times within the next couple of weeks…

**Comment by bbodenmiller** [comment]
Looks to be fixed.
