### ISSUE TITLE
ensure new schedule data is updated before schedule changes

### ISSUE THREAD

**Issue by bbodenmiller** [SoundTransit/soundtransit-rds#7]
Word on Twitter and around is that OBA's schedule data typically takes a bit to get updated after new schedules start. Would be great if a process could be created to ensure the new schedules are ready in OBA on day 0.

**Comment by sheldonabrown** [comment]
We now have a process to respond to GTFS updates/issues, deploy to OBA, and update the public facing GTFS in mere hours if necessary.  I'm going to close this issue barring any complaints.

**Comment by bbodenmiller** [comment]
FYI appears some of the Google datas gone stale:

![image](https://cloud.githubusercontent.com/assets/1192780/8029816/120b9a74-0d76-11e5-9c5b-e0f3c1921598.jpg)

/cc @bdferris
